import { createApp } from 'vue';
import App from './App.vue';
const app = createApp(App);
import 'amfe-flexible/index.js';
import Vant from 'vant';
import 'vant/lib/index.css';
app.use(Vant);
app.use(router);
import router from './router';
import store from './store';
app.use(store);
import axiosReq from '@/utils/axiosReq';
app.config.globalProperties.$axiosReq = axiosReq;
import 'virtual:svg-icons-register';
import svgIcon from '@/icons/SvgIcon.vue';
app.component('SvgIcon', svgIcon);
import $momentMini from 'moment-mini';
app.config.globalProperties.$momentMini = $momentMini;
import directive from '@/directive';
directive(app);
import '@/styles/index.scss';
import './permission';
app.mount('#app');
